<?php

namespace Database\Seeders;

use App\Models\MeasurementUnit;
use Illuminate\Database\Seeder;

class MeasurementUnitSeeder extends Seeder
{
    public function run(): void
    {
        $units = [
            // ─── Ingredient units ───────────────────────────────────────────
            [
                'type'        => 'ingredient',
                'code'        => 'kg',
                'icon'        => '⚖️',
                'sort_order'  => 1,
                'name_uz'     => 'Kilogram',
                'name_uz_cyrl'=> 'Килограмм',
                'name_ru'     => 'Килограмм',
                'name_kk'     => 'Килограмм',
                'name_ky'     => 'Килограмм',
                'name_tr'     => 'Kilogram',
                'example_uz'  => 'Non, somsa, shashlik uchun un, go\'sht — kg da o\'lchanadi',
                'example_ru'  => 'Мука, мясо для хлеба, самсы, шашлыка — измеряется в КГ',
            ],
            [
                'type'        => 'ingredient',
                'code'        => 'g',
                'icon'        => '🔬',
                'sort_order'  => 2,
                'name_uz'     => 'Gramm',
                'name_uz_cyrl'=> 'Грамм',
                'name_ru'     => 'Грамм',
                'name_kk'     => 'Грамм',
                'name_ky'     => 'Грамм',
                'name_tr'     => 'Gram',
                'example_uz'  => 'Tuz, moy, ziravorlar kabi kichik miqdordagi ingredientlar uchun',
                'example_ru'  => 'Для небольших объёмов: соль, масло, специи',
            ],
            [
                'type'        => 'ingredient',
                'code'        => 'ta',
                'icon'        => '🔢',
                'sort_order'  => 3,
                'name_uz'     => 'Dona',
                'name_uz_cyrl'=> 'Дона',
                'name_ru'     => 'Штука',
                'name_kk'     => 'Дана',
                'name_ky'     => 'Даана',
                'name_tr'     => 'Adet',
                'example_uz'  => 'Tuxum, bulochka, somsa, non turlari — dona hisobida',
                'example_ru'  => 'Яйца, булочки, самсы — поштучный учёт',
            ],
            [
                'type'        => 'ingredient',
                'code'        => 'l',
                'icon'        => '💧',
                'sort_order'  => 4,
                'name_uz'     => 'Litr',
                'name_uz_cyrl'=> 'Литр',
                'name_ru'     => 'Литр',
                'name_kk'     => 'Литр',
                'name_ky'     => 'Литр',
                'name_tr'     => 'Litre',
                'example_uz'  => 'Sut, yog\', sharbat, ichimliklar uchun litrda hisoblash',
                'example_ru'  => 'Молоко, масло, соки, напитки — измеряется в литрах',
            ],
            [
                'type'        => 'ingredient',
                'code'        => 'ml',
                'icon'        => '🧪',
                'sort_order'  => 5,
                'name_uz'     => 'Millilitr',
                'name_uz_cyrl'=> 'Миллилитр',
                'name_ru'     => 'Миллилитр',
                'name_kk'     => 'Миллилитр',
                'name_ky'     => 'Миллилитр',
                'name_tr'     => 'Mililitre',
                'example_uz'  => 'Aromatizatorlar, siroplar, kichik hajmli suyuqliklar uchun',
                'example_ru'  => 'Ароматизаторы, сиропы, небольшие объёмы жидкостей',
            ],
            [
                'type'        => 'ingredient',
                'code'        => 'm',
                'icon'        => '📏',
                'sort_order'  => 6,
                'name_uz'     => 'Metr',
                'name_uz_cyrl'=> 'Метр',
                'name_ru'     => 'Метр',
                'name_kk'     => 'Метр',
                'name_ky'     => 'Метр',
                'name_tr'     => 'Metre',
                'example_uz'  => 'Qadoqlash materiallari, lenta, boshqa uzunlik o\'lchovlari uchun',
                'example_ru'  => 'Упаковочные материалы, лента и другие линейные измерения',
            ],

            // ─── Batch / volume units ────────────────────────────────────────
            [
                'type'        => 'batch',
                'code'        => 'qop',
                'icon'        => '🎒',
                'sort_order'  => 1,
                'name_uz'     => 'Qop',
                'name_uz_cyrl'=> 'Қоп',
                'name_ru'     => 'Мешок',
                'name_kk'     => 'Қап',
                'name_ky'     => 'Кап',
                'name_tr'     => 'Çuval',
                'example_uz'  => 'Novvoylar bir partiyada necha qop un ishlatganini hisoblaydi. Masalan: "3 qop un ishlatdim"',
                'example_ru'  => 'Пекари считают партиями: "использовал 3 мешка муки"',
            ],
            [
                'type'        => 'batch',
                'code'        => 'blok',
                'icon'        => '📦',
                'sort_order'  => 2,
                'name_uz'     => 'Blok',
                'name_uz_cyrl'=> 'Блок',
                'name_ru'     => 'Блок',
                'name_kk'     => 'Блок',
                'name_ky'     => 'Блок',
                'name_tr'     => 'Blok',
                'example_uz'  => 'Qadoqlangan mahsulotlar blok-blok hisoblanadi. Masalan: "2 blok bulochka"',
                'example_ru'  => 'Расфасованная продукция: "2 блока булочек"',
            ],
            [
                'type'        => 'batch',
                'code'        => 'bolim',
                'icon'        => '🗂️',
                'sort_order'  => 3,
                'name_uz'     => 'Bo\'lim',
                'name_uz_cyrl'=> 'Бўлим',
                'name_ru'     => 'Партия',
                'name_kk'     => 'Партия',
                'name_ky'     => 'Партия',
                'name_tr'     => 'Parti',
                'example_uz'  => 'Ishlab chiqarish jarayonida partiyalar: "1 bo\'lim go\'shtli mahsulot tayyordim"',
                'example_ru'  => 'Производственные партии: "1 партия мясной продукции"',
            ],
            [
                'type'        => 'batch',
                'code'        => 'quti',
                'icon'        => '🗃️',
                'sort_order'  => 4,
                'name_uz'     => 'Quti',
                'name_uz_cyrl'=> 'Қути',
                'name_ru'     => 'Ящик',
                'name_kk'     => 'Қорап',
                'name_ky'     => 'Куту',
                'name_tr'     => 'Kutu',
                'example_uz'  => 'Shirinliklar, tort va qandolat mahsulotlari qutilarda saqlanadi',
                'example_ru'  => 'Сладости, торты и кондитерские изделия хранятся в ящиках/коробках',
            ],
            [
                'type'        => 'batch',
                'code'        => 'toplam',
                'icon'        => '📚',
                'sort_order'  => 5,
                'name_uz'     => 'To\'plam',
                'name_uz_cyrl'=> 'Тўплам',
                'name_ru'     => 'Комплект',
                'name_kk'     => 'Топлам',
                'name_ky'     => 'Топтом',
                'name_tr'     => 'Set',
                'example_uz'  => 'Bir to\'plam mahsulot — masalan, qadoqli set',
                'example_ru'  => 'Комплект продукции, например набор в упаковке',
            ],
            [
                'type'        => 'batch',
                'code'        => 'km',
                'icon'        => '🛣️',
                'sort_order'  => 6,
                'name_uz'     => 'Kilometr',
                'name_uz_cyrl'=> 'Километр',
                'name_ru'     => 'Километр',
                'name_kk'     => 'Километр',
                'name_ky'     => 'Километр',
                'name_tr'     => 'Kilometre',
                'example_uz'  => 'Yetkazib berish yoki chiziqli o\'lchov talab qilganda',
                'example_ru'  => 'Доставка или линейный учёт',
            ],
            [
                'type'        => 'batch',
                'code'        => 'ton',
                'icon'        => '⚓',
                'sort_order'  => 7,
                'name_uz'     => 'Tonna',
                'name_uz_cyrl'=> 'Тонна',
                'name_ru'     => 'Тонна',
                'name_kk'     => 'Тонна',
                'name_ky'     => 'Тонна',
                'name_tr'     => 'Ton',
                'example_uz'  => 'Katta hajm — tonna bo\'yicha hisoblash',
                'example_ru'  => 'Крупные объёмы — учёт в тоннах',
            ],
            [
                'type'        => 'batch',
                'code'        => 'm3',
                'icon'        => '📐',
                'sort_order'  => 8,
                'name_uz'     => 'Kubometr',
                'name_uz_cyrl'=> 'Куб метр',
                'name_ru'     => 'Куб. метр',
                'name_kk'     => 'Куб метр',
                'name_ky'     => 'Куб метр',
                'name_tr'     => 'm³',
                'example_uz'  => 'Hajm bo\'yicha — suv, shag\'al, qum va hokazo',
                'example_ru'  => 'Объёмный учёт',
            ],
        ];

        foreach ($units as $data) {
            MeasurementUnit::updateOrCreate(
                ['code' => $data['code']],
                $data,
            );
        }
    }
}
